### ISSUE TITLE
NOT WORKING??????

### ISSUE THREAD

**Issue by Sadlittlelad** [YourMajestyTheEye/Bookarklets#1]
It stopped working

**Comment by YourMajestyTheEye** [comment]
Which ones?

**Comment by Sadlittlelad** [comment]
all of them for me. I never changed them. they just stopped working 2 days after i bookmarked them.

**Comment by YourMajestyTheEye** [comment]
Hmm that's weird, maybe your school blocked bookmarklets. Try deleting and rebookmarking them. I just added another one that unblocked restricted videos on YouTube, so you could try that and see if it works.
